Update build-and-release.yml
Fixes release_count blocking at 31

diff --git a/.github/workflows/build-and-release.yml b/.github/workflows/build-and-release.yml
--- a/.github/workflows/build-and-release.yml
+++ b/.github/workflows/build-and-release.yml
@@ -24,8 +24,28 @@ jobs:
       - name: 🔢 Get number of releases this month
         id: get_release_count
         run: |
-          release_count=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases | jq -r "[.[] | select(.tag_name | startswith(\"${{ steps.date.outputs.date }}\"))] | length")
-          echo "count=$((release_count + 1))" >> $GITHUB_OUTPUT
+          page=1
+          release_count=0
+            
+          while :; do
+            response=$(curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${{ steps.repo_name.outputs.lowercase }}/releases?per_page=100&page=$page")
+            echo "Raw response (firstchars):"
+            echo "$RESPONSE" | head -c 1500
+            count=$(echo "$response" | jq -r "[.[] | select(.tag_name | startswith(\"${{ steps.date.outputs.date }}\"))] | length")
+             
+            # Check if count is an integer before adding to release_count
+            if ! [[ "$count" =~ ^[0-9]+$ ]]; then
+              echo "Error: count is not a valid integer"
+              exit 1
+            fi
+
+            release_count=$((release_count + count))
+            
+            [ "$count" -lt 100 ] && break
+            page=$((page + 1))
+          done
+            
+          echo "count=$release_count" >> $GITHUB_OUTPUT
 
       - name: 🏷️ Set version
         id: set_version
